### ISSUE TITLE
Can't Play Songs With Non-ascii Chars. in Path in Python 3

### ISSUE THREAD

**Issue by marky1991** [devsnd/cherrymusic#368]
In python 3.3, when I try to play a song from a folder with a name with accents, it fails to play, giving an (thousands, actually) error on the client side of the form "Playback failed! trying to resume from the point it failed." (There's no exception on the server side displayed in the console)

E.g. this fails:
/Español/Me Interesas.mp3

But this does not:
/Favoritas/Me Interesas.mp3

(Note: The two files' contents are identical)

Similarly, /Favoritas/Solo Me Importas Tú.mp3 fails but Favoritas/Solo Me Importas Tu.mp3 plays. (Again, the contents of the two files are the same)

I saw the overall unicode issue, but that was specifically referring to python 2 and similar tickets seem to assume that it works properly in Python 3.

If necessary, you can verify directly: http://marky1991.dyndns.org:8081/ (username: test, password: test)

**Comment by hank** [comment]
Ran into this today:
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/logging/__init__.py", line 980, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 308-310: ordinal not in range(128)
Call stack:
  File "/usr/lib/python3.4/threading.py", line 888, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/srv/cherrymusic/cherrymusicserver/util.py", line 49, in wrapper
    result = func(*args, **kwargs)
  File "/srv/cherrymusic/cherrymusicserver/sqlitecache.py", line 470, in full_update
    self.update_db_recursive(cherry.config['media.basedir'], skipfirst=True)
  File "/srv/cherrymusic/cherrymusicserver/sqlitecache.py", line 539, in update_db_recursive
    self.register_file_with_db(item.infs)
  File "/srv/cherrymusic/cherrymusicserver/sqlitecache.py", line 311, in register_file_with_db
    log.e(_("wrong encoding for filename '%s' (%s)"), fileobj.relpath, e.__class__.__name__)
  File "/srv/cherrymusic/cherrymusicserver/log.py", line 126, in error
    _get_logger().error(msg, *args, **kwargs)
Message: "wrong encoding for filename '%s' (%s)"
Arguments: ('Albums/Lindsey Stirling/Lindsey Stirling (V0)/02 Zi-Zi\udce2\udc80\udc99s Journey.mp3', 'UnicodeEncodeError')
```
The filename is as follows:
02 Zi-Zi’s Journey.mp3

The single quote is a UTF-8 curly:
http://www.fileformat.info/info/unicode/char/2019/index.htm
Unicode Character 'RIGHT SINGLE QUOTATION MARK' (U+2019)

It's a good test case to make sure UTF8 works.  Let me know if I can help - I'm halfway decent at python.
