### ISSUE TITLE
0.35.1 - Failed to load file browser

### ISSUE THREAD

**Issue by xMinerv** [devsnd/cherrymusic#544]
Hey guys,
I updated my server to 0.35.1, start the server, then login and browse files. Im prompted with: Failed to load file browser.

I am running cherrymusic through screen. My startup is: "screen -d -m -S cherrymusic -t cherrymusic /usr/bin/python3 /home/user/cherrymusic/cherrymusic"

Stack is:
[150415-17:06] ERROR   : [15/Apr/2015:17:06:57] HTTP Traceback (most recent call last):
  File "/home/user/cherrymusic/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/home/user/cherrymusic/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/user/cherrymusic/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/user/cherrymusic/cherrymusicserver/httphandler.py", line 290, in api
    return json.dumps({'data': handler(**handler_args)})
TypeError: api_listdir() missing 1 required positional argument: 'directory'

Thank you all for your hard work!

**Comment by 6arms1leg** [comment]
Hello @xMinerv,

please see #530. :twisted_rightwards_arrows:

**Comment by xMinerv** [comment]
Yeah i did see #530. I also noticed that he did not put any useful
information in the thread, so i added my comments in.

uhh.. Thanks though.

**Comment by tilboerner** [comment]
@xMinerv: I bet that's indeed the missing information for the other issue. Very good, thank you!
