### ISSUE TITLE
.m4a files not supported by tinytag?

### ISSUE THREAD

**Issue by mikeder** [devsnd/cherrymusic#563]
On CherryMusic 0.35.2 album art fetching seems broken for .m4a files.

Here is my log output when attempting to fetch:

```
[150523-05:11] Fetching album art for: M-N-O-P/Other Echoes/Other Echoes/1-02 You'll Be My Medicine (feat. Al.m4a                                                                         
[150523-05:11] ERROR   : [23/May/2015:05:11:42] HTTP Traceback (most recent call last):       
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/_cprequest.py", line 656, in respond 
    response.body = self.handler()                                                             
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/lib/encoding.py", line 188, in __call__ 
    self.body = self.oldhandler(*args, **kwargs)                                               
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)                                            
  File "/home/cherrymusic/cherrymusic-devel/cherrymusicserver/httphandler.py", line 289, in api 
    return handler(**handler_args)                                                             
  File "/home/cherrymusic/cherrymusic-devel/cherrymusicserver/httphandler.py", line 404, in 
    api_fetchalbumart  tag = TinyTag.get(filepath, image=True)                                                    
  File "/home/cherrymusic/cherrymusic-devel/tinytag/tinytag.py", line 82, in get                 
    raise LookupError('No tag reader found to support filetype! ')                          
LookupError: No tag reader found to support filetype!
```

This is the first time I've noticed this being broken, I'm not sure if it's new or has been this way for some time. Do .m4a files show album art as expected for you guys?

**Comment by devsnd** [comment]
Hi mike, thanks for your report!

Tinytag does not yet support m4a, but CM tries to fetch the meta data of any playable song anyway, so the bug is rather that CM does not catch that error properly.

**Comment by systems-rebooter** [comment]
Haven't noticed this issue earlier and just  created request for supporting m4a in tt repo, lol :-)

**Comment by systems-rebooter** [comment]
Voting this up :octocat:

**Comment by devsnd** [comment]
Please follow the issue in the tiny tag repository for any updates: https://github.com/devsnd/tinytag/issues/18
