### ISSUE TITLE
Cherrymusic crash

### ISSUE THREAD

**Issue by pando85** [devsnd/cherrymusic#581]
It crash today and last trace is this:
```
[08/Jul/2015:11:10:33] HTTP Traceback (most recent call last):
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/cherrymusic/cherrymusic-devel/cherrymusicserver/httphandler.py", line 289, in api
    return handler(**handler_args)
  File "/home/cherrymusic/cherrymusic-devel/cherrymusicserver/httphandler.py", line 404, in api_fetchalbumart
    tag = TinyTag.get(filepath, image=True)
  File "/home/cherrymusic/cherrymusic-devel/tinytag/tinytag.py", line 85, in get
    tag.load(tags=tags, duration=duration, image=image)
  File "/home/cherrymusic/cherrymusic-devel/tinytag/tinytag.py", line 102, in load
    self._parse_tag(self._filehandler)
  File "/home/cherrymusic/cherrymusic-devel/tinytag/tinytag.py", line 254, in _parse_tag
    self._parse_id3v1(fh)
  File "/home/cherrymusic/cherrymusic-devel/tinytag/tinytag.py", line 292, in _parse_id3v1
    self.genre = ID3.ID3V1_GENRES[genre_id]
IndexError: list index out of range

```
I think is not for this, but in the server.log file and error.log there are not more 'relevant' information.

**Comment by pando85** [comment]
This is happening to me more often now, could be a problem with my virtual machine?
This is the dmesg:
```
[    7.998171] FS-Cache: Loaded
[    8.038327] piix4_smbus 0000:00:01.3: SMBus Host Controller at 0xb100, revision 0
[    8.074947] RPC: Registered named UNIX socket transport module.
[    8.074957] RPC: Registered udp transport module.
[    8.074960] RPC: Registered tcp transport module.
[    8.075006] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    8.162433] FS-Cache: Netfs 'nfs' registered for caching
[    8.271741] Installing knfsd (copyright (C) 1996 okir@monad.swb.de).
[    8.648661] init: idmapd-mounting (/home/cherrymusic/Music) main process (262) killed by TERM signal
[    8.788912] kvm: Nested Virtualization enabled
[    8.947242] [drm] Initialized drm 1.1.0 20060810
[    9.306212] [TTM] Zone  kernel: Available graphics memory: 251822 kiB
[    9.306214] [TTM] Initializing pool allocator
[    9.306223] [TTM] Initializing DMA pool allocator
[    9.306813] [drm] fb mappable at 0x0
[    9.306814] [drm] vram aper at 0x0
[    9.306815] [drm] size 0
[    9.306816] [drm] fb depth is 24
[    9.306817] [drm]    pitch is 3072
[    9.617224] fbcon: cirrusdrmfb (fb0) is primary device
[    9.797600] Console: switching to colour frame buffer device 128x48
[    9.877885] cirrus 0000:00:02.0: fb0: cirrusdrmfb frame buffer device
[    9.877888] cirrus 0000:00:02.0: registered panic notifier
[    9.877905] [drm] Initialized cirrus 1.0.0 20110418 for 0000:00:02.0 on minor 0
[   11.509836] init: Failed to obtain startpar-bridge instance: Unknown parameter: INSTANCE
[   11.703470] init: failsafe main process (464) killed by TERM signal
[   12.462431] init: statd-mounting (/home/cherrymusic/Music) main process (263) killed by TERM signal
[   12.649309] NFS: Registering the id_resolver key type
[   12.649359] Key type id_resolver registered
[   12.649363] Key type id_legacy registered
[   13.381084] RPC: AUTH_GSS upcall failed. Please check user daemon is running.
[   13.771796] init: plymouth-upstart-bridge main process ended, respawning

```

**Comment by devsnd** [comment]
I've updated tinytag to the newest version and this bug should now be fixed in the devel branch.

**Comment by pando85** [comment]
Thanks devsnd great job, I will inform you if all is ok for me.

**Comment by pando85** [comment]
:( Now the server does not crash, but It stop in some songs and it can't reproduce them.
```
[19/Jul/2015:18:23:26]  Traceback (most recent call last):
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/_cprequest.py", line 102, in run
    hook()
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/_cprequest.py", line 62, in __call__
    return self.callback(**self.kwargs)
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/_cptools.py", line 176, in _wrapper
    if self.callable(**kwargs):
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/lib/static.py", line 319, in staticdir
    handled = _attempt(filename, content_types)
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/lib/static.py", line 246, in _attempt
    serve_file(filename, content_type=content_type, debug=debug)
  File "/home/cherrymusic/cherrymusic-devel/cherrymusicserver/__init__.py", line 162, in serve_file_utf8_fix
    disposition, name, debug)
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/lib/static.py", line 92, in serve_file
    fileobj = open(path, 'rb')
PermissionError: [Errno 1] Operation not permitted: '/home/cherrymusic/.local/share/cherrymusic/basedir/Alex/Mi Música/Oi!/kaos urbano/KAOS URBANO- El orden del kaos/KAOS URBANO-  El orden del kaos/03 - La memoria de los vencidos.mp3'

[19/Jul/2015:18:23:26] HTTP Traceback (most recent call last):
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/_cprequest.py", line 653, in respond
    self.hooks.run('before_handler')
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/_cprequest.py", line 112, in run
    raise exc
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/_cprequest.py", line 102, in run
    hook()
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/_cprequest.py", line 62, in __call__
    return self.callback(**self.kwargs)
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/_cptools.py", line 176, in _wrapper
    if self.callable(**kwargs):
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/lib/static.py", line 319, in staticdir
    handled = _attempt(filename, content_types)
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/lib/static.py", line 246, in _attempt
    serve_file(filename, content_type=content_type, debug=debug)
  File "/home/cherrymusic/cherrymusic-devel/cherrymusicserver/__init__.py", line 162, in serve_file_utf8_fix
    disposition, name, debug)
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/lib/static.py", line 92, in serve_file
    fileobj = open(path, 'rb')
PermissionError: [Errno 1] Operation not permitted: '/home/cherrymusic/.local/share/cherrymusic/basedir/Alex/Mi Música/Oi!/kaos urbano/KAOS URBANO- El orden del kaos/KAOS URBANO-  El orden del kaos/03 - La memoria de los vencidos.mp3'

[19/Jul/2015:18:23:26]  Traceback (most recent call last):
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/_cprequest.py", line 102, in run
    hook()
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/_cprequest.py", line 62, in __call__
    return self.callback(**self.kwargs)
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/_cptools.py", line 176, in _wrapper
    if self.callable(**kwargs):
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/lib/static.py", line 319, in staticdir
    handled = _attempt(filename, content_types)
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/lib/static.py", line 246, in _attempt
    serve_file(filename, content_type=content_type, debug=debug)
  File "/home/cherrymusic/cherrymusic-devel/cherrymusicserver/__init__.py", line 162, in serve_file_utf8_fix
    disposition, name, debug)
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/lib/static.py", line 92, in serve_file
    fileobj = open(path, 'rb')
PermissionError: [Errno 1] Operation not permitted: '/home/cherrymusic/.local/share/cherrymusic/basedir/Alex/Mi Música/Oi!/kaos urbano/KAOS URBANO- El orden del kaos/KAOS URBANO-  El orden del kaos/03 - La memoria de los vencidos.mp3'

[19/Jul/2015:18:23:26] HTTP Traceback (most recent call last):
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/_cprequest.py", line 653, in respond
    self.hooks.run('before_handler')
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/_cprequest.py", line 112, in run
    raise exc
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/_cprequest.py", line 102, in run
    hook()
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/_cprequest.py", line 62, in __call__
    return self.callback(**self.kwargs)
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/_cptools.py", line 176, in _wrapper
    if self.callable(**kwargs):
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/lib/static.py", line 319, in staticdir
    handled = _attempt(filename, content_types)
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/lib/static.py", line 246, in _attempt
    serve_file(filename, content_type=content_type, debug=debug)
  File "/home/cherrymusic/cherrymusic-devel/cherrymusicserver/__init__.py", line 162, in serve_file_utf8_fix
    disposition, name, debug)
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/lib/static.py", line 92, in serve_file
    fileobj = open(path, 'rb')
PermissionError: [Errno 1] Operation not permitted: '/home/cherrymusic/.local/share/cherrymusic/basedir/Alex/Mi Música/Oi!/kaos urbano/KAOS URBANO- El orden del kaos/KAOS URBANO-  El orden del kaos/03 - La memoria de los vencidos.mp3'
```

**Comment by 6arms1leg** [comment]
Do you (or more precisely the user that runs CherryMusic) have read permissions on the audio files mentioned in your log above?

**Comment by pando85** [comment]
It has, the problem is with some tracks but I don't see nothing weird (name or tags)

**Comment by tilboerner** [comment]
Hmm... Missing access permissions for files are usually `[Errno 13] Permission Denied`. `[Errno 1] Operation not permitted` means that the cherrymusic process is lacking some capability [(see EPERM examples)](http://lxr.free-electrons.com/ident?i=EPERM). @pando85: Is there another resource/device involved? Something on USB maybe?

This is likely an issue outside of our control; but let's try to bring some light into it and make sure. Some other, more general questions:

Are all files in a common directory affected? Any symlinks or networked filesystems involved along the path? Is it consistently the same files that don't work? (Meaning also that they never work?) I'm not sure if you meant earlier that the tracks actually start playing; do they always stop around the same time, or do they never even start?

**Comment by pando85** [comment]
I don't sure if it is related with permissions because same files with same permissions in the same folder can or can't be played randomly. But if one file can't be played it NEVER can't be played. This come with last update of tinytag because before this I could play all files, but before update my cherrymusic crash sometimes (only in the last 2 weeks).

#Additional information:
My cherrymusic is running in a dedicated virtual machine with ubuntu server, Linux 3.13.0-49-generic. The music folder is mounted in the virtual machine by nfs with only read permissions, but this is not the problem because that was working properly and I have other services with the same structure.

**Comment by pando85** [comment]
I want to add that tracks that can be played say 'PermissionError' too but its log file is not repeating it all time. In tracks that can't be played it is repeting each 0.5s in log file.

**Comment by pando85** [comment]
I don't know why but now it's working properly. I close this... I think it could be a problem with my system but I don't know what one.
