### ISSUE TITLE
Error when trying to compile less

### ISSUE THREAD

**Issue by bmbrands** [devsnd/cherrymusic#625]
When trying to compile some custom less css I get this error. Perhaps I am running it from the wrong path (I am running it in the base folder of cherrymusic). I have read the docs and could not figure this one out. I hope this is not a really stupid question.

```
osmc@midio:~/cherrymusic$ devscripts/deploy.py 
lessc: no input files

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: EBADF: bad file descriptor, read
    at Error (native)
Traceback (most recent call last):
  File "devscripts/deploy.py", line 87, in <module>
    html = develhtml.read()
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 4784: ordinal not in range(128)
```

**Comment by rubencabrera** [comment]
Have you tried to pass the less file as an argument to the deploy.py ? 

I might be horribly wrong, but it looks like argparser is being used and some functions don't have a default fallback, so specifying input and output (css resulting file) files for less compiler might go at least a step forward.

If this is stupid and doesn't solve anything, then I can only suggest attacking the other part of the error message:

Have you tried to check your system locale as sugested in #611 ?

Is your less file using a standard encoding? Is the encoding stated anywhere with `@charset` ?

**Comment by bmbrands** [comment]
Thanks. I have set the locale to en_US.UTF-8 and ran the script again.
This time it appeared to work!
My res/devel.html was compiled to res/dist/main.html (Note: in the WIKI it says it compiles to res/main.html)

I still see these:

`lessc: no input files

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: EBADF: bad file descriptor, read
    at Error (native)`

But I can continue trying to change the UI!

Thanks for helping!

**Comment by rubencabrera** [comment]
Glad I could help. But I can't find that events.js file, any suggestion on that so I can try and handle the error?

**Comment by bmbrands** [comment]
Hmm yes that's weird.

When I do 
```
sudo find / -name "events.js"
```
I get 0 results

When I do 
```
me@midi:~/cherrymusic: grep -ir 'events.js' . 
```
I just find one reference:
```
./res/js/ext/jquery.jplayer.js: //https://developer.apple.com/library/safari/samplecode/HTML5VideoEventFlow/Listings/events_js.html#//apple_ref/doc/uid/DTS40010085-events_js-DontLinkElementID_5
```

So no idea what that is.

**Comment by devsnd** [comment]
Hey Everybody,

This error started to show up a few node.js versions ago for me as well. But it seems it does not interfere with the actual compilation process, so I did not bother to investigate myself...

By the way, if you find outdated Wiki contents, feel free to edit them.

**Comment by devsnd** [comment]
I'm closing this issue because of inactivity for now so that the issue tracker is not filled up with stale issues. Feel free to reopen this issue. :fish:
