### ISSUE TITLE
CMD BUG 2-22-17

### ISSUE THREAD

**Issue by tylerhoot** [devsnd/cherrymusic#660]
hate to be the barer of bad news...
-------------------------------------------------------------------------------------------------------
[170222-15:00] ERROR   : [22/Feb/2017:15:00:25] HTTP Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\cherrymusic-devel\cherrypy\_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "C:\Users\Administrator\Desktop\cherrymusic-devel\cherrypy\lib\encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\cherrymusic-devel\cherrypy\_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\Users\Administrator\Desktop\cherrymusic-devel\cherrymusicserver\httphandler.py", line 290, in api
    handler_args = json.loads(kwargs['data'])
  File "C:\Program Files\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python36\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 1 column 21 (char 20)

-----------------------------------------------------------------------------------------------------------
 "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0"
[170222-15:05] ERROR   : [22/Feb/2017:15:05:14] ENGINE Error in background task thread function <bound method FileSession.clean_up of <cherrypy.lib.sessions.FileSession object at 0x0000022B71137C18>>.
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\cherrymusic-devel\cherrypy\process\plugins.py", line 482, in run
    self.function(*self.args, **self.kwargs)
  File "C:\Users\Administrator\Desktop\cherrymusic-devel\cherrypy\lib\sessions.py", line 494, in clean_up
    contents = self._load(path)
  File "C:\Users\Administrator\Desktop\cherrymusic-devel\cherrypy\lib\sessions.py", line 441, in _load
    return pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 1: ordinal not in range(128)

Exception in thread Session cleanup:
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\Desktop\cherrymusic-devel\cherrypy\process\plugins.py", line 482, in run
    self.function(*self.args, **self.kwargs)
  File "C:\Users\Administrator\Desktop\cherrymusic-devel\cherrypy\lib\sessions.py", line 494, in clean_up
    contents = self._load(path)
  File "C:\Users\Administrator\Desktop\cherrymusic-devel\cherrypy\lib\sessions.py", line 441, in _load
    return pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 1: ordinal not in range(128)

[170222-15:05] 192.168.1.189 - - [22/Feb/2017:15:05:18] "POST /api/heartbeat HTTP/1.1" 200 14 "http://192.168.1.2:8070/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0"

**Comment by tilboerner** [comment]
This is the very same thing as in #651, which you closed for some reason. I'm reopening it. :) We extracted all the information from this error message, reposting it won't do much, I'm afraid. 

Please, to help us fix this, could you do what I wrote in the very last paragraph in my last comment over there?
