### ISSUE TITLE
Error on run - invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by nebbishOne** [devsnd/cherrymusic#720]
I have been running Cherrymusic v0.39.1 on a Ras Pi model 3, on raspbian Jesse for a long time. This week, my external USB drive died and I had to replace it with a new one. The old drive was mounted at /media/BIGDRIVE and the new drive is setup at /media/BIGDRIVE2 now. That's where my music library is stored so that seems relevant. 

CherryMusic now aborts on start up with:

 ```
~ $ python /opt/cherrymusic/cherrymusic --port 8989

Traceback (most recent call last):
  File "/opt/cherrymusic/cherrymusic", line 236, in <module>
    cherrymusicserver.start_server(ConfigOptions.configdict)
  File "/opt/cherrymusic/cherrymusicserver/__init__.py", line 290, in start_server
    CherryMusic(cfg_override)
  File "/opt/cherrymusic/cherrymusicserver/__init__.py", line 351, in __init__
    CherryMusic.create_pid_file()
  File "/opt/cherrymusic/cherrymusicserver/__init__.py", line 379, in create_pid_file
    os.getpgid(int(pidfile.read()))
ValueError: invalid literal for int() with base 10: ''
```

I've re-run the --setup option and that seemed to go fine, but it still fails to start. 

Thanks for any help. Love this software!

**Comment by nebbishOne** [comment]
Ignore this. All set here.

I fixed this error by removing the cherrymusic.pid file from the ./local/share/cherrymusic folder. Now the app starts up just fine. I'll leave this here for someone else just in case.
